---
- name: ensure percona-toolkit is installed
  hosts: 127.0.0.1
  vars_files:
    - hosts.localhost
  connection: local
  roles:
    - percona_toolkit

- name: test out MySQL server after upgrade
  hosts: all
  serial: 1
  max_fail_percentage: 1
  roles:
    - mysql_tests
